### ISSUE TITLE
UI

### ISSUE THREAD

**Issue by FlederJ** [Sub-game-team/Subgame#46]
Create a main screen and an inventory to display all the different items like the torpedos, railguns, maybe the current reactor and the energy levels

**Comment by zockerhuhn** [comment]
Please only create branches when you start working on the issue, this prevents unnecessary commits to update an old branch or creates merge conflicts
@FlederJ

**Comment by FlederJ** [comment]
Closed because it was assigned to a nonexistent branch and didnt work.
